### ISSUE TITLE
Trouble Executing Commands in Docker Container

### ISSUE THREAD

**Issue by rodycaymond** [digitalist-se/extratools#37]
As I'm working through the setup guide at https://plugins.matomo.org/ExtraTools#documentation, I keep getting stuck on activating the ExtraTools plugin. A screenshot of the error can be seen below. The error is mentioning something about a Zend_Db_Adapater_Exception where it can't find a file or directory. The ExtraTools Repo is in the proper location. I.E. /var/www/html/plugins. Through various google searches, I'm simply unable to find a remedy to this error, and am therefore completely blocked from continuing with the setup. Some context, I am containerizing matomo with the official matomo docker image and an accompanying database, all in a docker-compose. The screenshot you're seeing is from the matomo container after sh'ing into it. I am attempting to completely automate the setup of matomo with multiple known sites to track for development purposes. In a perfect world, all of this is done via docker-compose so its repeatable for all my fellow devs. I've setup a "post entrypoint" script to handle the remainder of the setup after the container has initialized matomo, where all of the setup commands from the ExtraTools docs are being ran. I have basically no experience with php applications, so all of this is very new to me. Have you seen this before? Any suggestions?

![Screenshot 2023-09-13 at 4 21 59 PM](https://github.com/digitalist-se/extratools/assets/58873401/8b16b9a0-8d4a-4cb7-9490-45002c755df3)

**Comment by jorgeuos** [comment]
Hello @rodycaymond !

First of all! I'm really glad you found this plugin and you are completely right on track! Setting up Matomo can be very cumbersome and the point of this plugin is to make it hazzle free to automate. So big KUDOS! 🙌🏼

The problem you're experiencing, seems related to MySQL not running properly.

Steps to troubleshoot:

1. Double check your `config/config.ini.php` that you are getting the right credentials.
    I'm assuming you are running a separate DB service in your docker-compose. Make sure your config is pointing to that service with the right credentials.
2. Ensure you have the PDO and PDO-MySQL extensions installed and enabled in PHP. You can verify this by creating a `phpinfo.php` file with the following content:
php
```php
<?php phpinfo(); ?>
```
If not, you can add it(if you are using a custom Dockerfile)
```Dockerfile
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-source extract \
    && docker-php-ext-install pdo pdo_mysql \
    && docker-php-source delete
```

If nothing works, could you share your `docker-compose.yml` file or a repo(if public) and I can troubleshoot further.

And lastly, don't loose you hair over this, I've probably seen this a hundred times and the issue is almost always starring you in the face.

**Comment by mikkeschiren** [comment]
As we haven't heard from you for a while @rodycaymond - I will close this issue. Please reopen if the issue still isn't solved.
