### ISSUE TITLE
Make "matomo:install" to detect if Matomo already installed.

### ISSUE THREAD

**Issue by cwchristerw** [digitalist-se/extratools#43]
I would like to automate installation process with Ansible and I would need way to install from CLI. I would like to have option to use --force but only when Matomo isn't installed already.

**Comment by mikkeschiren** [comment]
If you use --force - and Matomo is already installed, it will still work. We are doing this - or do you have issues with this?

**Comment by cwchristerw** [comment]
I was wondering if you are using matomo:install --force does it check if Matomo is already installed and not install it again. I need this feature that work similarly to matomo:install --force but only when Matomo isn't installed already.

This matomo:install --force or similar would only add config file when it's missing and database has Matomo installed.

**Comment by mikkeschiren** [comment]
This is what is happening - If Matomo is installed - It does run install - but it doesn't destroy anything if you add the the flag `--do-not-drop-db` - that is - equals to doing an  update. But before `matom install` - you should run `core:update` so you also are sure you will get the latest plugins update.

**Comment by cwchristerw** [comment]
Would it be possible to run core:update before running matomo:install because I need to order command in a way its possible to run uninstalled and installed Matomo instance? Currently I have added in this order following commands `/var/www/html/console matomo:install --do-not-drop-db --force` and `/var/www/html/console core:update`. I believe it's not possible to run core:update without having config and in my current setup config is newly generated by matomo:install every time when  Matomo container is recreated.

**Comment by mikkeschiren** [comment]
Understand, this is in the scope of something we are working on at this moment in our Helm chart, maybe it could be something added in this plugin. I will come back on the subject.

**Comment by mbrodala** [comment]
@cwchristerw The `core:update` command is shipped by Matomo itself and strictly requires the DB schema to exist. OTOH the `matomo:install` command provided by this plugin can be called safely on an empty DB **as well as** a DB with an existing schema and data.

So what is the issue exactly?

**Comment by cwchristerw** [comment]
I really dont have any problems this was just wondering if its okay to run matomo:install everytime I create container with Ansible playbook. I need to have one flow that works with both new and existing Matomo instances.

https://github.com/Digitalist-Open-Cloud/Matomo-Plugin-ExtraTools/issues/43#issuecomment-2426557869
Also this comment mentioned that I should run core:update before matomo:install, but it's not possible. :smile:

Is there any downsides on running matomo:install command everytime I start container? If I would use `--do-not-drop-db --force`.

I'm technically reinstalling Matomo when updating container :smile:

**Comment by mbrodala** [comment]
Yeah, basically that is what happens.

---

However, the install procedure graciously skips existing DB data:

https://github.com/Digitalist-Open-Cloud/Matomo-Plugin-ExtraTools/blob/f7458f6ab8a56f61245bc3219c5f618f563eefc9/Lib/Install.php#L269-L270

Same goes for the creation of the 1st (super) user:

https://github.com/Digitalist-Open-Cloud/Matomo-Plugin-ExtraTools/blob/f7458f6ab8a56f61245bc3219c5f618f563eefc9/Lib/Install.php#L336-L337

Plugin uninstallation is a special feature of the ExtraTools plugin which is the only thing that really can drop DB data. However, if you use this, you normally are well-aware what it does. Also it requires usage of a JSON install file instead of pure CLI/env.

https://github.com/Digitalist-Open-Cloud/Matomo-Plugin-ExtraTools/blob/f7458f6ab8a56f61245bc3219c5f618f563eefc9/Lib/Install.php#L436

---

So all in all from reading and actually using, it should be safe to run `matomo:install` on an existing installation. In case I missed something, please let me know.
